CREATE TABLE IF NOT EXISTS mpa (
  mpa_id int PRIMARY KEY,
  name varchar(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS  genre (
  genre_id int PRIMARY KEY,
  name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    description varchar(300) NOT NULL,
    release_date date NOT NULL,
    duration int NOT NULL,
    mpa_id int NOT NULL,
    CONSTRAINT mpa_fk
        FOREIGN KEY (mpa_id)
            REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100) NOT NULL,
    login varchar(50) NOT NULL,
    name varchar(50) NOT NULL,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship (
  user_id   int NOT NULL,
  friend_id int NOT NULL,
  CONSTRAINT friendship_pk
      PRIMARY KEY (user_id, friend_id),
  CONSTRAINT friendship_users_user_id_fk
      FOREIGN KEY (user_id)
           REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT friendship_users_friend_id_fk
      FOREIGN KEY (friend_id)
           REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id int NOT NULL,
    user_id int NOT NULL,
    CONSTRAINT films_likes_pk
        PRIMARY KEY (film_id, user_id),
    CONSTRAINT films_likes_films_film_id_fk
        FOREIGN KEY (film_id)
            REFERENCES films(film_id) ON DELETE CASCADE,
    CONSTRAINT films_likes_users_user_id_fk
        FOREIGN KEY (user_id)
            REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  film_genres (
    film_id int NOT NULL,
    genre_id int NOT NULL,
    CONSTRAINT film_genre
        PRIMARY KEY (film_id, genre_id),
    CONSTRAINT film_genres_genre_id_fk
        FOREIGN KEY (genre_id)
            REFERENCES genre(genre_id),
    CONSTRAINT film_genres_film_id_fk
        FOREIGN KEY (film_id)
            REFERENCES films(film_id) ON DELETE CASCADE
);
